### PR TITLE
make doug talk

### PR DESCRIPTION
**Pull request by SteveHNH**

### CODE REVIEW

**Review by justinorringer — CHANGES_REQUESTED** [review]
image

The box looks great, but I can't interact again to get out of the dialog haha.

**Review by aleccohan — COMMENTED** [review]
Yeah!  looks like i'm having the same issue as Justin.  Though it looks like the enter key will let you escape from the text box.

**Comment by josejulio** [comment]
I guess we are only missing some indications `<press enter to continue>`

**Comment by SteveHNH** [comment]
thanks, ya'll. I'll fix it. I got excited that I could get the dialogue in there lol

**Review by aleccohan — APPROVED** [review]
Ayyyyy!!  Yup!  That works now!

**Pull request merged**
